### ISSUE TITLE
Nice !

### ISSUE THREAD

**Issue by FGRibreau** [phlegx/redlics#1]
Nice one @phlegx !

Redilics will be shared in our next [RedisWeekly](http://redisweekly.com/)! Once published (in a matter of minutes) you will be able to see your [projet here](http://redisweekly.com/archive/141.html) :)

**Comment by phlegx** [comment]
Thank you @FGRibreau! Monday I add the documentation how to use the gem. :smile:

**Comment by FGRibreau** [comment]
:+1:

**Comment by phlegx** [comment]
Here the documentation https://github.com/phlegx/redlics#redlics :smile:
